### ISSUE TITLE
Markdown not escaping in answers

### ISSUE THREAD

**Issue by ChillarAnand** [omouse/emacs-sos#13]
when i fetch an answer from sos, markup tags are not escaping. it looks like this 

    *** Answer no. 1
    <p><strong>Maximum peer connections limit is 256 (on chrome).</strong></p>

    <p>Not sure about other major browsers, depending on your bandwidth they are limited to give certain stability.</p>

Any idea how to solve this?

**Comment by omouse** [comment]
it's related to #6 post-processing to filter out HTML tags. closing since it's a duplicate of that issue.
